### ISSUE TITLE
Explain `popup_cards` better

### ISSUE THREAD

**Issue by johntdyer** [DBuit/light-popup-card#11]
Hello,

 Its not clear to me how I am supposed to use `popup_cards` and if that is related in any way w/ `popup-card` or `browser-mod`.  Is there a hello world like example that shows this template (?) defined and then used in a view within lovelace that I am somehow overlooking ? 

thanks

**Comment by DBuit** [comment]
He John,

So i made this card to work with my other card: https://github.com/DBuit/Homekit-panel-card
to get more home kit style interface.

But i use card tools by thomas loven so the card can also be used without my other card. And just as a popup in your interface.

So it works with popup-card and browser-mod by thomas and the example code in the readme is how you can use it with browser-mod:

```
popup_cards:
  light.beganegrond:
    title: ""
    style:
      position: fixed
      z-index: 999
      top: 0
      left: 0
      height: 100%
      width: 100%
      display: block
      align-items: center
      justify-content: center
      background: rgba(0, 0, 0, 0.8)
      flex-direction: column
      margin: 0
      "--iron-icon-fill-color": "#FFF"
    card:
      type: custom:light-popup-card
      entity: light.beganegrond
      icon: mdi:led-strip
      scenesInARow: 2
      brightnessWidth: 150px
      brightnessHeight: 400px
      switchWidth: 150px
      switchHeight: 400px
      scenes:
        - scene: scene.ontspannen
          color: "#FDCA64"
          name: ontspannen
        - scene: scene.helder
          color: "#FFE7C0"
          name: helder
        - scene: scene.concentreren
          color: "#BBEEF3"
        - scene: scene.energie
          color: "#8BCBDD"
```

Here you got the section about the popup in the browser_mod readme: https://github.com/thomasloven/hass-browser_mod#popup

Hope you can get it working let me know if i can help you!
