### ISSUE TITLE
Slider at 100% doesn't set it to 255 in backend

### ISSUE THREAD

**Issue by Petro31** [DBuit/light-popup-card#24]
Title says it all.  When maximized via sliding, the value placed into the backend is between 251 and 255.  Most of the lights in my configuration get set to 252 which is 99%, making it impossible to set to 100%.

I'm just using the default style provided in the example.
```
  light.bonus_room_office_fixture:
    title: ""
    style:
      position: fixed
      z-index: 999
      top: 0
      left: 0
      height: 100%
      width: 100%
      display: block
      align-items: center
      justify-content: center
      background: rgba(0, 0, 0, 0.5)
      flex-direction: column
      margin: 0
    card:
      type: custom:light-popup-card
      entity: light.bonus_room_office_fixture
      icon: None
      sliderTrackColor: var(--paper-item-icon-color)
      sliderThumbColor: var(--paper-item-icon-color)
```
