### ISSUE TITLE
Feature Request: allow data template as service call

### ISSUE THREAD

**Issue by ASNNetworks** [DBuit/light-popup-card#63]
It would be great if you could use a data_template as an entity_id.  This would be great with cards like decluttering-card and auto-entities. For instance:

```
        - icon: 'mdi:link-plus'
          color: var(--background-color)
          service:  squeezebox.sync
          service_data:
            entity_id: "{{states.media_player.lms_speakers.attributes.active_child}}"      
            other_player: media_player.lms
```

I hope this can be also added to the other popup cards (media_player and cover).
