### ISSUE TITLE
Only works with browser_mod...

### ISSUE THREAD

**Issue by clemalex824** [DBuit/light-popup-card#72]
Beautiful card. 

After reading title card I understand that it is for browser_mod.

When I use it alone, no card is displayed (it is present in raw editor but not in view).

Would it be possible to make this card work outside of browser_mod ?

On the forum thread, the designer replied that it was a card like any other, Unfortunately it does not appear outside of browser_mod. 

Is this possible to add the possibility to display this card without browser_mod like a normal card ?

**Comment by clemalex824** [comment]
Just add this card in ab entities card :+1:

```
      type: entities
      entities:
        - type: custom:light-popup-card
          entity: light.desk
          icon: none
          fullscreen: false
          brightnessWidth: 130px
          brightnessHeight: 360px
          borderRadius: 1.7em
          sliderColor: '#c7c7c7'
          sliderTrackColor: rgba(25, 25, 25, 0.9)
```

Thanks a lot for this card
