### ISSUE TITLE
Makes scenes part more configurable by adding option to call a service with service data instead of just a scene

### ISSUE THREAD

**Issue by DBuit** [DBuit/light-popup-card#9]
- [x] Makes scenes part more configurable by adding option to call a service with service data instead of just a scene

**Comment by CM000n** [comment]
Can you maybe extend the Scenes please also with types like "input_boolean" and "switch"? I have for example some input_booleans that trigger some automations for controlling my circadian lightning.

**Comment by isabellaalstrom** [comment]
Tip: Extend it to take service call and service data, so the user can choose whichever service they want. It will be easier for you to implement as well I think, instead of taking everything into account separately.

Like these: https://www.home-assistant.io/lovelace/entity-button/#service
example:
```
  service: script.turn_on
  service_data:
    entity_id: script.turn_off_lights

**Comment by dacorn** [comment]
I would agree with that! Almost all my button-cards are calling services. 

DBuit I love what you have done I’m now using your cards on my home. 

Dave

**Comment by CM000n** [comment]
I agree. You are absolutely right @isabellaalstrom.
Much better than taking everything into account.

**Comment by DBuit** [comment]
Thanks for the suggestion i did what you suggested @isabellaalstrom 
new version released: https://github.com/DBuit/light-popup-card/releases/tag/0.2.2

**Comment by septeven** [comment]
Great addition @DBuit but unfortunately it sounds like it won't match my needs.
I initially asked if you can add a feature which supports scripts because I have scripts using data_template that I would like to call but I can't use data_template under service_data you've implemented...

To explain myself, I did scripts which reproduce the Hue defaults scene, using template so I can define which light entity has to be impacted while calling the script :

```
script:
  scene_concentration:
    alias: '[HUE SCENE] Concentration'
    sequence:
      - service: light.turn_on
        data_template:
          entity_id: '{{light_id}}'
          rgb_color: [255, 240, 198]
          brightness: 254
```
Any idea how I can use your feature with my setup ?
