### ISSUE TITLE
Instead of the dimming function, the on/off button

### ISSUE THREAD

**Issue by aLAN-LDZ** [DBuit/light-popup-card#96]
Hello, I have a problem because instead of the dimming option, the on / off button is displayed

code:

```
: fire-dom-event
browser_mod:
  service: browser_mod.popup
  data:
    card_mod:
      style:
        #popup header
        .:
    content:
      type: custom:light-popup-card
      entity: light.sufit
```

the lamp is dimmable and RGB and it works in the rest of the home assistant
